import assert from 'node:assert/strict';
import { demoSurvey } from '../src/export.js';
import { runFullQaqc } from '../src/qaqc.js';
import { buildFieldDebrief, renderFieldDebriefBody, renderFieldDebriefDocument } from '../src/debrief.js';

const demo = demoSurvey();
const survey = { id: 'debrief-demo', mission: demo.mission, site: demo.site };
const qaqc = runFullQaqc(survey, demo.records, { require_environment_per_station: true, bbox: {} });
const debrief = buildFieldDebrief(survey, demo.records, qaqc, true);
assert.equal(debrief.qa.label, 'Passed');
assert.equal(debrief.counts.stations, 1);
assert.equal(debrief.counts.transects, 1);
assert.equal(debrief.counts.observations, 1);
assert.equal(debrief.effort.transectLengthM, 25);
assert.equal(debrief.effort.trackDistanceM, 41.7);
assert.equal(debrief.effort.observedIndividuals, 7);
assert.ok(debrief.environment.some((metric) => metric.label === 'Water temperature'));
assert.equal(debrief.keyObservations[0].label, 'Atlantic silverside');
assert.ok(debrief.mapHtml.includes('mission-map'));
const body = renderFieldDebriefBody(debrief, [], { preview: true });
assert.ok(body.includes('EcoSurvey field debrief'));
assert.ok(body.includes('Field geometry'));
assert.ok(body.includes('Environmental range'));
const document = renderFieldDebriefDocument(debrief, []);
assert.ok(document.includes('Print / Save as PDF'));
assert.ok(document.includes('@page{size:letter landscape'));
const stale = buildFieldDebrief(survey, demo.records, qaqc, false);
assert.equal(stale.qa.label, 'Stale');
console.log('Field-debrief report smoke test passed.');
